import com.google.protobuf.gradle.*

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.ulalax.playhouse.kotlin-library-conventions")
}

group =  Versions.groupId
version = Versions.version

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = Versions.groupId
            artifactId = "playhouse"
            version = Versions.version
            from(components["java"])
        }
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${Versions.protocVersion}"
    }
    generateProtoTasks {
        all().forEach {
            it.builtins {
                id("kotlin")
            }
        }
    }
}

dependencies {
    api(project(":common"))
    implementation(Depend.lettuce)
    implementation(Depend.commonsValidator)
    implementation("org.reflections:reflections:0.10.2")
    implementation("io.netty:netty-all:4.1.90.Final")
    implementation(kotlin("reflect"))
    runtimeOnly("org.jetbrains.kotlin:kotlin-reflect:1.7.20")

    testApi(project(":clientConnector"))
    testImplementation("org.springframework:spring-context:6.0.6")
    testImplementation("org.testcontainers:junit-jupiter:1.17.6")
    testImplementation("org.slf4j:slf4j-simple:2.0.6")
}

