import com.google.protobuf.gradle.*

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.ulalax.playhouse.kotlin-library-conventions")
}


group =  Versions.groupId
version = Versions.version

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = Versions.groupId
            artifactId = "playhouse"
            version = Versions.version
            from(components["java"])
        }
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${Versions.protocVersion}"
    }
}

sourceSets {
    main {
        proto {
            srcDir ("./proto")
        }
        java {
            srcDirs(
                "build/generated/source/proto/main/java"
            )
        }
    }
}



dependencies {
    api(project(":protocol"))
    api(project(":zmq"))
//    implementation("org.zeromq:jmq:1.0")
    implementation(Depend.lettuce)
    implementation(Depend.commonsValidator)
    implementation("org.reflections:reflections:0.10.2")
    implementation("io.netty:netty-all:4.1.79.Final")
    implementation("org.springframework:spring-context:5.3.22")
    // https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-reflect
    runtimeOnly("org.jetbrains.kotlin:kotlin-reflect:1.7.20")

    // https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core

    testImplementation("it.ozimov:embedded-redis:0.7.3")
    testApi(project(":clientConnector"))
    implementation(kotlin("reflect"))
}


