/*
 * This file was generated by the Gradle 'init' task.
 */
import com.google.protobuf.gradle.*


plugins {
    id("org.ulalax.playhouse.kotlin-library-conventions")
}


group =  Versions.groupId
version = Versions.version


java {
    withSourcesJar()
    withJavadocJar()
}


publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = Versions.groupId
            artifactId = "protocol"
            version = Versions.version
            from(components["java"])
        }
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${Versions.protocVersion}"
    }
    generateProtoTasks {
        all().forEach {
            it.builtins {
                id("kotlin")
            }
        }
    }
}


dependencies {
//    implementation("org.zeromq:zmqj:4.3.4.1")
    // https://mvnrepository.com/artifact/it.ozimov/embedded-redis
    //implementation("org.zeromq:jmq:1.0")
//    api(project(":zmq"))

}
