/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.lifemmo.pl.base.kotlin-library-conventions")

}

group =  Versions.groupId
version = Versions.version

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = Versions.groupId
            artifactId = "zmq"
            version = Versions.version
            from(components["java"])
        }
    }
}