/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.ulalax.playhouse.kotlin-library-conventions")

}

group =  Versions.groupId
version = Versions.version

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = Versions.groupId
            artifactId = "zmq"
            version = Versions.version
            from(components["java"])
        }
    }
}